Areas/Admin/Controllers/RoleController.cs
using DocumentFormat.OpenXml.Office2010.Excel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using StockManagementMVC.Repository;
using System;

namespace StockManagementMVC.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class RoleController : Controller
    {

        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly DataContext _dbContext;
        public RoleController(DataContext dbContext, RoleManager<IdentityRole> roleManager)
        {
            _dbContext = dbContext;
            _roleManager = roleManager;
        }
        public IActionResult Index()
        {
            var roles = _roleManager.Roles.ToList();
            return View(roles);
        }
        [HttpGet]
        public IActionResult Create()
        {

            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string Name)
        {
            if (!string.IsNullOrWhiteSpace(Name))
            {
                var result = await _roleManager.CreateAsync(new IdentityRole(Name));
                if (result.Succeeded)
                    return RedirectToAction("Index");
                foreach (var error in result.Errors)
                    ModelState.AddModelError("", error.Description);
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            return View(role);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, string name)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                role.Name = name;
                var result = await _roleManager.UpdateAsync(role);
                if (result.Succeeded)
                    return RedirectToAction("Index");
            }
            return View(role);
        }

    }
}

Areas/Admin/Controllers/SupplierController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StockManagementMVC.Models;
using StockManagementMVC.Repository;

namespace StockManagementMVC.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin,Nhân viên")]
    [Area("Admin")]
    public class SupplierController : Controller
    {
        private readonly DataContext _dbContext;
        public SupplierController(DataContext dbContext)
        {
            _dbContext = dbContext;
        }
        public IActionResult Index()
        {
            var suppliers = _dbContext.Supplier.ToList();
            return View(suppliers);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(SupplierModel supplier)
        {
            if (ModelState.IsValid)
            {
                var supplierModel = new SupplierModel();

                _dbContext.Supplier.Add(supplier);
                _dbContext.SaveChanges();
                TempData["SuccessMessage"] = "Thêm nhà cung cấp thành công.";
                return RedirectToAction("Index");
            }
            return View(supplier);
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var supplier = _dbContext.Supplier.Find(id);
            return View(supplier);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(SupplierModel supplier)
        {
            if (ModelState.IsValid)
            {
                _dbContext.Supplier.Update(supplier);
                _dbContext.SaveChanges();
                TempData["SuccessMessage"] = "Cập nhật nhà cung cấp thành công.";
                return RedirectToAction("Index");
            }
            return View(supplier);
        }
        [HttpPost]
        public IActionResult Delete(int id)
        {
            var supplier = _dbContext.Supplier.Find(id);
            if (supplier != null)
            {
                _dbContext.Supplier.Remove(supplier);
                _dbContext.SaveChanges();
                TempData["SuccessMessage"] = "Xóa nhà cung cấp thành công.";
            }
            return RedirectToAction("Index");
        }
    }
}

Areas/Admin/Controllers/UserController.cs
using DocumentFormat.OpenXml.Office2010.Excel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using StockManagementMVC.Models.ViewModel;

namespace StockManagementMVC.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class UserController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        public UserController(UserManager<IdentityUser> userManager)
        {
            _userManager = userManager;

        }
        public IActionResult Index()
        {
            var users = _userManager.Users.ToList();
            return View(users);
        }
        [HttpGet]
        public IActionResult Create() => View();

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            var currentUserId = _userManager.GetUserId(User); // ID của user đang đăng nhập

            if (id == currentUserId)
            {
                TempData["ErrorMessage"] = "Không thể sửa chính tài khoản của bạn.";
                return RedirectToAction("Index");
            }

            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            var model = new UserEditViewModel
            {
                Id = user.Id,
                Email = user.Email
            };

            return View(model);


        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(UserEditViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var user = await _userManager.FindByIdAsync(model.Id);

            if (user == null)
            {
                return NotFound();
            }

            // Nếu có password mới, thì đổi password
            if (!string.IsNullOrEmpty(model.NewPassword))
            {
                var token = await _userManager.GeneratePasswordResetTokenAsync(user);
                var resetResult = await _userManager.ResetPasswordAsync(user, token, model.NewPassword);
                if (!resetResult.Succeeded)
                {
                    foreach (var error in resetResult.Errors)
                        ModelState.AddModelError("", error.Description);
                    return View(model);
                }
            }

            TempData["SuccessMessage"] = "Cập nhật người dùng thành công";
            return RedirectToAction("Index");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(UserViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new IdentityUser { UserName = model.Email, Email = model.Email };
                var result = await _userManager.CreateAsync(user, model.Password);

                if (result.Succeeded)
                {
                    TempData["Success"] = "Tạo người dùng thành công";
                    return RedirectToAction("Index");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            var currentUserId = _userManager.GetUserId(User); // ID của user đang đăng nhập

            if (id == currentUserId)
            {
                TempData["ErrorMessage"] = "Không thể xóa chính tài khoản của bạn.";
                return RedirectToAction("Index");
            }
            var user = await _userManager.FindByIdAsync(id);

            if (user == null) return NotFound();


            // Xóa user
            var result = await _userManager.DeleteAsync(user);
            TempData["SuccessMessage"] = "Đã xóa người dùng thành công";
            return RedirectToAction("Index");
        }

    }
}

Areas/Admin/Controllers/UserRoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using StockManagementMVC.Models;
using StockManagementMVC.Models.ViewModel;
using StockManagementMVC.Repository;
using System;

namespace StockManagementMVC.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class UserRoleController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly DataContext _dbContext;
        public UserRoleController(
            UserManager<IdentityUser> userManager,
            RoleManager<IdentityRole> roleManager,
            DataContext dbContext)
        {
            _dbContext = dbContext;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public async Task<IActionResult> Index()
        {
            var users = _userManager.Users.ToList();
            var model = new List<UserWithRolesViewModel>();

            foreach (var user in users)
            {
                var roles = await _userManager.GetRolesAsync(user);
                model.Add(new UserWithRolesViewModel
                {
                    User = user,
                    Roles = roles.ToList()
                });
            }

            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Manage(string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);

            var roles = _roleManager.Roles.ToList();

            var userRoles = await _userManager.GetRolesAsync(user);

            var model = new UserRolesViewModel
            {
                UserId = user.Id,
                UserEmail = user.Email,

                Roles = roles.Select(role => new RoleSelection
                {
                    RoleName = role.Name,
                    IsSelected = userRoles.Contains(role.Name)
                }).ToList()
            };

            return View(model);
        }
        // POST: Gán quyền
        [HttpPost]
        public async Task<IActionResult> Manage(UserRolesViewModel model)
        {
            var user = await _userManager.FindByIdAsync(model.UserId); //A
            var userRoles = await _userManager.GetRolesAsync(user); //A - Admin

            var selectedRoles = model.Roles.Where(r => r.IsSelected).Select(r => r.RoleName).ToList(); //Admin //f8a03ec5-c2be-4ff8-80ae-7f1f4782cf02

            var result = await _userManager.AddToRolesAsync(user, selectedRoles.Except(userRoles));

            await _userManager.RemoveFromRolesAsync(user, userRoles.Except(selectedRoles)); //A - Nhânvien

            TempData["Message"] = "Cập nhật quyền thành công.";
            return RedirectToAction("Index");
        }

    }
}

Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StockManagementMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StockManagementMVC.styles.css" asp-append-version="true" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">StockManagementMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                       @*  <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> *@
                         @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-primary" asp-area="" asp-controller="Account" asp-action="Logout">Đăng xuất: @User.Identity.Name</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-primary" asp-area="Admin" asp-controller="Dashboard" asp-action="Index">CMS</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-info" asp-area="Admin" asp-controller="Product" asp-action="Index"><i class="fas fa-box"></i> Sản phẩm</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-info" asp-area="Admin" asp-controller="Warehouse" asp-action="Import"><i class="fa-solid fa-warehouse"></i> Nhập kho</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-info" asp-area="Admin" asp-controller="Warehouse" asp-action="Export"><i class="fa-solid fa-warehouse"></i> Xuất kho</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-info" asp-area="Admin" asp-controller="Supplier" asp-action="Index"><i class="fa-solid fa-warehouse"></i> Nhà cung cấp</a>
                            </li>
                             <li class="nav-item">
                                <a class="nav-link text-info" asp-area="Admin" asp-controller="User" asp-action="Index"><i class="fa-solid fa-user"></i> Users</a>
                            </li>
                             <li class="nav-item">
                                <a class="nav-link text-info" asp-area="Admin" asp-controller="Role" asp-action="Index"><i class="fa-solid fa-user"></i> Roles</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-info" asp-area="Admin" asp-controller="UserRole" asp-action="Index"><i class="fa-solid fa-user"></i> Gán vai trò</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Đăng ký</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Đăng nhập</a>
                            </li>
                        }
                      
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @if (TempData["ErrorMessage"] != null)
            {
                <div class="alert alert-danger">
                    @TempData["ErrorMessage"]
                </div>
            }
            else if (TempData["SuccessMessage"] != null)
            {
                <div class="alert alert-success">
                    @TempData["SuccessMessage"]
                </div>
            }
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - StockManagementMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>